import static br.com.finalproject.TransactionFile.readFile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "WELCOME TO YOUR BANK TRANSACTIONS!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        readFile();

        //generate extracts after executeOperations()


    }
}
